apiVersion: v1
kind: Service
metadata:
  name: crosswords
spec:
  selector:
    app: crosswords
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: 35.225.5.206
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crosswords
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: crosswords
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: crosswords
    spec:
      containers:
      - env:
        - name: MONGODB
          valueFrom:
            configMapKeyRef:
              key: MONGODB
              name: boobtree-config-4cyc
        image: gcr.io/prefab-conquest-186122/crosswords@sha256:ce6839845a231a0d17902c45352db0dffde7c25522a2806c958e553738cf7597
        imagePullPolicy: IfNotPresent
        name: crosswords-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
